### ISSUE TITLE
Where is the train-dataset and test-dataset folders?

### ISSUE THREAD

**Issue by shreyasmishra1998** [Mahmood-Hoseini/COVID19-CT-Scan-Segmentation#3]
In your notebook you have mentioned train and test dataset folders. How to get them?

**Comment by Mahmood-Hoseini** [comment]
I am still updating some of the codes. Depending on my schedule, it may take couple days. I'll put all the data somewhere for you to access.

**Comment by shreyasmishra1998** [comment]
Thanks for your prompt reply.
